UPDATE Alimentos SET fat = 3.6, calories = 165, serving_size = 100, unit = 'g', category = 'Carnes' WHERE name = 'Frango Grelhado';
UPDATE Alimentos SET fat = 1.3, calories = 135, serving_size = 100, unit = 'g', category = 'Carnes' WHERE name = 'Peito de Peru';
UPDATE Alimentos SET fat = 13.1, calories = 206, serving_size = 100, unit = 'g', category = 'Peixe' WHERE name = 'Salmão';
UPDATE Alimentos SET fat = 1.3, calories = 119, serving_size = 100, unit = 'g', category = 'Peixe' WHERE name = 'Atum em Conserva';
UPDATE Alimentos SET fat = 10.6, calories = 155, serving_size = 50, unit = 'un', category = 'Ovos' WHERE name = 'Ovo Cozido';
UPDATE Alimentos SET fat = 0.2, calories = 52, serving_size = 32, unit = 'un', category = 'Ovos' WHERE name = 'Clara de Ovo';
UPDATE Alimentos SET fat = 4.3, calories = 98, serving_size = 100, unit = 'g', category = 'Laticínios' WHERE name = 'Queijo Cottage';
UPDATE Alimentos SET fat = 5.0, calories = 102, serving_size = 100, unit = 'g', category = 'Laticínios' WHERE name = 'Iogurte Grego Natural';
UPDATE Alimentos SET fat = 0.1, calories = 36, serving_size = 100, unit = 'ml', category = 'Laticínios' WHERE name = 'Leite Magro';
UPDATE Alimentos SET fat = 3.9, calories = 61, serving_size = 100, unit = 'ml', category = 'Laticínios' WHERE name = 'Leite Gordo';
UPDATE Alimentos SET fat = 0.3, calories = 128, serving_size = 100, unit = 'g', category = 'Grãos' WHERE name = 'Arroz Branco Cozido';
UPDATE Alimentos SET fat = 0.9, calories = 111, serving_size = 100, unit = 'g', category = 'Grãos' WHERE name = 'Arroz Integral Cozido';
UPDATE Alimentos SET fat = 0.4, calories = 124, serving_size = 100, unit = 'g', category = 'Grãos' WHERE name = 'Massa Integral';
UPDATE Alimentos SET fat = 0.3, calories = 147, serving_size = 100, unit = 'g', category = 'Grãos' WHERE name = 'Massa Branca';
UPDATE Alimentos SET fat = 0.1, calories = 86, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Batata Doce';
UPDATE Alimentos SET fat = 0.1, calories = 77, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Batata Inglesa';
UPDATE Alimentos SET fat = 6.9, calories = 389, serving_size = 100, unit = 'g', category = 'Grãos' WHERE name = 'Aveia';
UPDATE Alimentos SET fat = 2.4, calories = 227, serving_size = 100, unit = 'g', category = 'Grãos' WHERE name = 'Pão Integral';
UPDATE Alimentos SET fat = 2.8, calories = 265, serving_size = 100, unit = 'g', category = 'Grãos' WHERE name = 'Pão Branco';
UPDATE Alimentos SET fat = 1.9, calories = 120, serving_size = 100, unit = 'g', category = 'Grãos' WHERE name = 'Quinoa';
UPDATE Alimentos SET fat = 0.5, calories = 132, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Feijão Preto Cozido';
UPDATE Alimentos SET fat = 2.6, calories = 164, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Grão-de-Bico Cozido';
UPDATE Alimentos SET fat = 0.4, calories = 116, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Lentilhas Cozidas';
UPDATE Alimentos SET fat = 0.4, calories = 81, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Ervilhas';
UPDATE Alimentos SET fat = 0.4, calories = 34, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Brócolos';
UPDATE Alimentos SET fat = 0.4, calories = 23, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Espinafres';
UPDATE Alimentos SET fat = 0.5, calories = 33, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Couve';
UPDATE Alimentos SET fat = 0.2, calories = 15, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Alface';
UPDATE Alimentos SET fat = 0.2, calories = 18, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Tomate';
UPDATE Alimentos SET fat = 0.2, calories = 41, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Cenoura';
UPDATE Alimentos SET fat = 0.1, calories = 16, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Pepino';
UPDATE Alimentos SET fat = 0.1, calories = 40, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Cebola';
UPDATE Alimentos SET fat = 0.5, calories = 149, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Alho';
UPDATE Alimentos SET fat = 0.3, calories = 31, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Pimento Vermelho';
UPDATE Alimentos SET fat = 0.3, calories = 22, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Cogumelos';
UPDATE Alimentos SET fat = 0.1, calories = 26, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Abóbora';
UPDATE Alimentos SET fat = 0.2, calories = 25, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Beringela';
UPDATE Alimentos SET fat = 0.4, calories = 17, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Courgette';
UPDATE Alimentos SET fat = 0.1, calories = 20, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Espargos';
UPDATE Alimentos SET fat = 0.3, calories = 89, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Banana';
UPDATE Alimentos SET fat = 0.2, calories = 52, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Maçã';
UPDATE Alimentos SET fat = 0.1, calories = 47, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Laranja';
UPDATE Alimentos SET fat = 0.3, calories = 32, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Morango';
UPDATE Alimentos SET fat = 0.3, calories = 57, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Mirtilos';
UPDATE Alimentos SET fat = 0.7, calories = 52, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Framboesa';
UPDATE Alimentos SET fat = 0.2, calories = 67, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Uvas';
UPDATE Alimentos SET fat = 0.1, calories = 30, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Melancia';
UPDATE Alimentos SET fat = 0.3, calories = 60, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Manga';
UPDATE Alimentos SET fat = 0.1, calories = 50, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Ananás';
UPDATE Alimentos SET fat = 0.5, calories = 61, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Kiwi';
UPDATE Alimentos SET fat = 0.2, calories = 39, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Pêssego';
UPDATE Alimentos SET fat = 0.1, calories = 57, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Pêra';
UPDATE Alimentos SET fat = 49.4, calories = 579, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Amêndoas';
UPDATE Alimentos SET fat = 65.2, calories = 654, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Nozes';
UPDATE Alimentos SET fat = 49.2, calories = 567, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Amendoains';
UPDATE Alimentos SET fat = 43.9, calories = 553, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Castanhas-de-Caju';
UPDATE Alimentos SET fat = 45.3, calories = 556, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Pistácios';
UPDATE Alimentos SET fat = 60.8, calories = 628, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Avelãs';
UPDATE Alimentos SET fat = 30.7, calories = 486, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Sementes de Chia';
UPDATE Alimentos SET fat = 42.2, calories = 534, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Sementes de Linhaça';
UPDATE Alimentos SET fat = 45.8, calories = 541, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Sementes de Abóbora';
UPDATE Alimentos SET fat = 51.5, calories = 584, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Sementes de Girassol';
UPDATE Alimentos SET fat = 50.4, calories = 588, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Manteiga de Amendoim';
UPDATE Alimentos SET fat = 100.0, calories = 900, serving_size = 15, unit = 'ml', category = 'Óleos' WHERE name = 'Azeite';
UPDATE Alimentos SET fat = 100.0, calories = 900, serving_size = 15, unit = 'ml', category = 'Óleos' WHERE name = 'Óleo de Coco';
UPDATE Alimentos SET fat = 14.7, calories = 160, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Abacate';
UPDATE Alimentos SET fat = 50.2, calories = 598, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Chocolate Negro 70%';
UPDATE Alimentos SET fat = 0.0, calories = 304, serving_size = 20, unit = 'colher', category = 'Comes' WHERE name = 'Mel';
UPDATE Alimentos SET fat = 1.0, calories = 333, serving_size = 30, unit = 'g', category = 'Comes' WHERE name = 'Proteína Whey';
UPDATE Alimentos SET fat = 2.0, calories = 308, serving_size = 30, unit = 'g', category = 'Comes' WHERE name = 'Proteína Vegetal';
UPDATE Alimentos SET fat = 5.0, calories = 233, serving_size = 50, unit = 'un', category = 'Comes' WHERE name = 'Barrinha Proteica';
UPDATE Alimentos SET fat = 0.0, calories = 24, serving_size = 100, unit = 'ml', category = 'Comes' WHERE name = 'Bebida Isotónica';
UPDATE Alimentos SET fat = 0.0, calories = 0, serving_size = 200, unit = 'ml', category = 'Comes' WHERE name = 'Café Preto';
UPDATE Alimentos SET fat = 0.0, calories = 0, serving_size = 200, unit = 'ml', category = 'Comes' WHERE name = 'Chá Verde';
UPDATE Alimentos SET fat = 0.2, calories = 46, serving_size = 100, unit = 'ml', category = 'Frutas' WHERE name = 'Água de Coco';
UPDATE Alimentos SET fat = 0.3, calories = 99, serving_size = 100, unit = 'g', category = 'Peixe' WHERE name = 'Camarão';
UPDATE Alimentos SET fat = 0.9, calories = 133, serving_size = 100, unit = 'g', category = 'Peixe' WHERE name = 'Polvo';
UPDATE Alimentos SET fat = 0.9, calories = 82, serving_size = 100, unit = 'g', category = 'Peixe' WHERE name = 'Lula';
UPDATE Alimentos SET fat = 0.7, calories = 105, serving_size = 100, unit = 'g', category = 'Peixe' WHERE name = 'Bacalhau';
UPDATE Alimentos SET fat = 10.5, calories = 208, serving_size = 100, unit = 'g', category = 'Peixe' WHERE name = 'Sardinha';
UPDATE Alimentos SET fat = 5.0, calories = 125, serving_size = 100, unit = 'g', category = 'Peixe' WHERE name = 'Dourada';
UPDATE Alimentos SET fat = 3.1, calories = 100, serving_size = 100, unit = 'g', category = 'Peixe' WHERE name = 'Robalo';
UPDATE Alimentos SET fat = 5.0, calories = 155, serving_size = 100, unit = 'g', category = 'Carnes' WHERE name = 'Carne de Vaca Magra';
UPDATE Alimentos SET fat = 4.0, calories = 149, serving_size = 100, unit = 'g', category = 'Carnes' WHERE name = 'Carne de Porco Magra';
UPDATE Alimentos SET fat = 6.0, calories = 162, serving_size = 100, unit = 'g', category = 'Carnes' WHERE name = 'Cordeiro';
UPDATE Alimentos SET fat = 4.2, calories = 130, serving_size = 100, unit = 'g', category = 'Carnes' WHERE name = 'Vitela';
UPDATE Alimentos SET fat = 11.5, calories = 215, serving_size = 100, unit = 'g', category = 'Carnes' WHERE name = 'Pato';
UPDATE Alimentos SET fat = 3.5, calories = 156, serving_size = 100, unit = 'g', category = 'Carnes' WHERE name = 'Coelho';
UPDATE Alimentos SET fat = 4.8, calories = 76, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Tofu';
UPDATE Alimentos SET fat = 11.0, calories = 195, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Tempeh';
UPDATE Alimentos SET fat = 1.5, calories = 370, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Seitan';
UPDATE Alimentos SET fat = 5.2, calories = 122, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Edamame';
UPDATE Alimentos SET fat = 21.3, calories = 264, serving_size = 100, unit = 'g', category = 'Laticínios' WHERE name = 'Feta';
UPDATE Alimentos SET fat = 17.1, calories = 280, serving_size = 100, unit = 'g', category = 'Laticínios' WHERE name = 'Mozzarella';
UPDATE Alimentos SET fat = 29.0, calories = 431, serving_size = 100, unit = 'g', category = 'Laticínios' WHERE name = 'Parmesão';
UPDATE Alimentos SET fat = 33.6, calories = 403, serving_size = 100, unit = 'g', category = 'Laticínios' WHERE name = 'Queijo Cheddar';
UPDATE Alimentos SET fat = 25.0, calories = 298, serving_size = 100, unit = 'g', category = 'Laticínios' WHERE name = 'Requeijão';
UPDATE Alimentos SET fat = 1.0, calories = 38, serving_size = 100, unit = 'g', category = 'Laticínios' WHERE name = 'Iogurte Natural';
UPDATE Alimentos SET fat = 1.0, calories = 37, serving_size = 100, unit = 'ml', category = 'Laticínios' WHERE name = 'Kefir';
UPDATE Alimentos SET fat = 37.0, calories = 340, serving_size = 100, unit = 'ml', category = 'Laticínios' WHERE name = 'Nata';
UPDATE Alimentos SET fat = 81.7, calories = 717, serving_size = 14, unit = 'g', category = 'Óleos' WHERE name = 'Manteiga';
UPDATE Alimentos SET fat = 0.6, calories = 112, serving_size = 100, unit = 'g', category = 'Grãos' WHERE name = 'Cuscuz';
UPDATE Alimentos SET fat = 0.4, calories = 83, serving_size = 100, unit = 'g', category = 'Grãos' WHERE name = 'Bulgur';
UPDATE Alimentos SET fat = 2.4, calories = 340, serving_size = 100, unit = 'g', category = 'Grãos' WHERE name = 'Farinha de Trigo Integral';
UPDATE Alimentos SET fat = 1.3, calories = 364, serving_size = 100, unit = 'g', category = 'Grãos' WHERE name = 'Farinha de Trigo Branca';
UPDATE Alimentos SET fat = 6.9, calories = 389, serving_size = 100, unit = 'g', category = 'Grãos' WHERE name = 'Farinha de Aveia';
UPDATE Alimentos SET fat = 49.4, calories = 579, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Farinha de Amêndoa';
UPDATE Alimentos SET fat = 0.3, calories = 102, serving_size = 100, unit = 'g', category = 'Grãos' WHERE name = 'Polenta';
UPDATE Alimentos SET fat = 0.0, calories = 358, serving_size = 100, unit = 'g', category = 'Grãos' WHERE name = 'Tapioca';
UPDATE Alimentos SET fat = 1.2, calories = 96, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Milho Cozido';
UPDATE Alimentos SET fat = 4.3, calories = 382, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Pipocas sem Sal';
UPDATE Alimentos SET fat = 1.3, calories = 168, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Castanhas';
UPDATE Alimentos SET fat = 0.2, calories = 282, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Tâmaras';
UPDATE Alimentos SET fat = 1.5, calories = 249, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Figos Secos';
UPDATE Alimentos SET fat = 0.5, calories = 299, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Passas';
UPDATE Alimentos SET fat = 0.5, calories = 241, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Damascos Secos';
UPDATE Alimentos SET fat = 0.4, calories = 240, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Ameixas Secas';
UPDATE Alimentos SET fat = 64.5, calories = 660, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Coco Ralado';
UPDATE Alimentos SET fat = 5.3, calories = 70, serving_size = 100, unit = 'g', category = 'Frutas' WHERE name = 'Açaí';
UPDATE Alimentos SET fat = 0.8, calories = 80, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Gengibre';
UPDATE Alimentos SET fat = 3.1, calories = 312, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Cúrcuma';
UPDATE Alimentos SET fat = 1.2, calories = 247, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Canela';
UPDATE Alimentos SET fat = 12.3, calories = 371, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Paprica';
UPDATE Alimentos SET fat = 14.6, calories = 375, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Cominho';
UPDATE Alimentos SET fat = 4.3, calories = 306, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Orégãos';
UPDATE Alimentos SET fat = 0.6, calories = 27, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Manjericão';
UPDATE Alimentos SET fat = 0.8, calories = 36, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Salsa';
UPDATE Alimentos SET fat = 0.5, calories = 23, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Coentros';
UPDATE Alimentos SET fat = 0.7, calories = 70, serving_size = 100, unit = 'g', category = 'Legumes' WHERE name = 'Hortelã';
UPDATE Alimentos SET fat = 15.2, calories = 331, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Alecrim';
UPDATE Alimentos SET fat = 7.4, calories = 276, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Tomilho';
UPDATE Alimentos SET fat = 0.0, calories = 68, serving_size = 15, unit = 'ml', category = 'Comes' WHERE name = 'Vinagre Balsâmico';
UPDATE Alimentos SET fat = 0.5, calories = 62, serving_size = 15, unit = 'ml', category = 'Comes' WHERE name = 'Molho de Soja';
UPDATE Alimentos SET fat = 3.3, calories = 66, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Mostarda';
UPDATE Alimentos SET fat = 0.1, calories = 112, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Ketchup';
UPDATE Alimentos SET fat = 5.0, calories = 67, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Maionese Light';
UPDATE Alimentos SET fat = 9.6, calories = 166, serving_size = 100, unit = 'g', category = 'Comes' WHERE name = 'Hummus';
